### ISSUE TITLE
#3

### ISSUE THREAD

**Issue by novachok** [MykhailoBaran/PHP_Lab#3]
https://github.com/MykhailoBaran/PHP_Lab/blob/master/PHP_3_Arrays/index.php#L7
цей кондішен тут не потрібен, тому що array_fill - з 1 прекрасно теж працює

**Comment by MykhailoBaran** [comment]
Десь читав що так швидше

**Comment by novachok** [comment]
так, це правда
але є ще інша штука - код має бути простим - і виграш перформенсу на пару мікросекунд не завжди вигідно
в будь якому разі - ця задача зарахована ;)
